### ISSUE TITLE
Will you take a PR that upgrades this library to netstandard v1.3?

### ISSUE THREAD

**Issue by ghuntley** [serilog/serilog-sinks-logentries#10]
i.e. add support for xamarin and uwp platforms

**Comment by nblumhardt** [comment]
Hi Geoffrey; absolutely. It'd be great to move this to the same `appveyor.yml` and `Build.ps1` that we now use for .NET Core support throughout the other Serilog projects (see serilog/serilog for example).

Adding netstandard1.3 shouldn't cost any compatibility with existing targets thanks to the flexibility of project.json.

I've updated the repo to have a default `dev` branch; that'd be the one to target. Let me know if you need any help.

Cheers!

**Comment by PureKrome** [comment]
Resolved with 8e8b863fa52bc8cab063c7d03600c4d6900227b7 ?

**Comment by nblumhardt** [comment]
:+1:

**Comment by nblumhardt** [comment]
@PureKrome thanks for checking it out. Any and all help appreciated :-)
