### ISSUE TITLE
LeClient uses synchronous writes

### ISSUE THREAD

**Issue by aguvenli** [serilog/serilog-sinks-logentries#20]
In LeClient.Cs, we have the following code:

` public void Write(byte[] buffer, int offset, int count){
            ActiveStream.Write(buffer, offset, count);
}`

In turn, the sync variant of EmitBatch is implemented in the sink. Is there a reason why the async implementation was not chosen?

**Comment by nblumhardt** [comment]
No reason that I'm aware of; a PR to improve thread pool usage would be great, if possible 👍

**Comment by kasper3** [comment]
@nblumhardt, if this issue is fixed, can we get a newer version of package with asynchronous fix please? Thank you!

**Comment by nblumhardt** [comment]
Thanks for the reminder to close this, @kasper3 :-)

Does https://www.nuget.org/packages/Serilog.Sinks.Logentries/3.0.27-dev-00034 work for you? If so, let me know - once we're happy nothing is broken in the pre-release package we can cut a new release 👍
