### ISSUE TITLE
HowTo: Read configuration from appsettings.json

### ISSUE THREAD

**Issue by critchie** [serilog/serilog-sinks-logentries#22]
I can't seem to find the right settings for my appsettings.json so that when I use: `ReadFrom.Configuration(Configuration)` in my Startup.cs, Logentries will read its settings from the configuration.

This is what I have currently:
```
    "WriteTo": [
      {
        "Name": "LogEntries",
        "Args": {
          "token": "MY-TOKEN",
          "formatProvider": "Serilog.Formatting.Json.JsonFormatter, Serilog",
          "restrictedToMinimumLevel": "Debug" 
        }
      }
    ]
```
I can't seem to find any clear instructions on how to do this.

**Comment by critchie** [comment]
I should note, my project is ASPNET Core 2.0,0 and is referencing:
Serilog.AspNetCore 2.0.0
Serilog.Settings.Configuration 2.4.0
Serilog.Sinks.Logentries 3.0.26

**Comment by RPM1984** [comment]
i'm also having similar issues, and have a similar setup (asp.net core 2.1). whatever i do, can't get it to write to LogEntries.

@critchie did you ever solve this? if not.. @nblumhardt could you please help 😊

**Comment by RPM1984** [comment]
@critchie awesome, that tool helped! i was missing this:
```
"Using": [ "Serilog.Sinks.Logentries" ],
```

thanks :)
