### ISSUE TITLE
Wrong Version Bug

### ISSUE THREAD

**Issue by NPSF3000** [serilog/serilog-sinks-logentries#6]
Trying to run Serilog 1.5.12 but this package gave me a lot of hard to debug issues:

_Could not load file or assembly 'Serilog, Version=1.4.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10' or one of its dependencies._

  Downloading the project and referencing the up-to-date serilog resolve the issue for now.

It's worth noting that this was a little tricky to diagnose as it would work when running as a stand-alone, but when I called this project as part of a bigger IIS project that's when the issue arose.

System.IO.FileLoadException was unhandled
  FileName=Serilog, Version=1.4.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10
  FusionLog==== Pre-bind state information ===
LOG: DisplayName = Serilog, Version=1.4.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10
 (Fully-specified)
LOG: Appbase = file:///C:/SourceControl/ExportApps/Services/bin/
LOG: Initial PrivatePath = NULL
Calling assembly : Serilog.Sinks.Logentries, Version=1.5.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10.
===
LOG: This bind starts in default load context.
LOG: No application configuration file found.
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Post-policy reference: Serilog, Version=1.4.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10
LOG: Attempting download of new URL file:///C:/SourceControl/ExportApps/Services/bin/Serilog.DLL.
WRN: Comparing the assembly name resulted in the mismatch: Minor Version
ERR: Failed to complete setup of assembly (hr = 0x80131040). Probing terminated.

  HResult=-2146234304
  Message=Could not load file or assembly 'Serilog, Version=1.4.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
  Source=Logging
  StackTrace:
       at Logging.Setup.ConfigureLogging(Boolean outputToConsole)
       at ExportHost.Program.Main(String[] args) in C:\SourceControl\ExportApps\ExportHost\Program.cs:line 29
  InnerException:

**Comment by nblumhardt** [comment]
Thanks for the report. A PR would be welcome to update the referenced Serilog version, if you're interested in posting one through?

**Comment by nblumhardt** [comment]
Hi again, I think we have this resolved with version 2.x of the package. Please let me know if you hit any other issues.

Regards,
Nick
